module.exports = {
    tags: [
        'binary search',
        'bitmasks',
        'brute force',
        'combinatorics',
        'constructive algorithms',
        'data structures',
        'dfs and similar',
        'divide and conquer',
        'dp',
        'games',
        'geometry',
        'graph matchings',
        'graphs',
        'greedy',
        'hashing',
        'implementation',
        'math',
        'matrices',
        'number theory',
        'probabilities',
        'shortest paths',
        'sortings',
        'strings',
        'ternary search',
        'trees',
        'two pointers'
    ]
}